baseURL = 'https://pablocasamianestudios.github.io/hugo_ejemplo/'
languageCode = 'en-us'
title = 'Sitio web de Pablo'

theme="relearn"

[[params.themeVariant]]
    identifier = 'neon'

[[params.themeVariant]]
    identifier = "blue"


